import os
from dotenv import load_dotenv
from github import Github, Auth
import chromadb
from openai import OpenAI

load_dotenv()

# Connect to GitHub
g = Github(auth=Auth.Token(os.getenv("GITHUB_TOKEN")))

# Connect to ChromaDB
chroma_client = chromadb.PersistentClient(path="./incident_db")
collection = chroma_client.get_or_create_collection("incidents")

# Connect to Zeabur
ai_client = OpenAI(
    api_key=os.getenv("ZEABUR_API_KEY"),
    base_url=os.getenv("ZEABUR_BASE_URL")
)

def find_similar_incidents(diff_text, n_results=3):
    results = collection.query(
        query_texts=[diff_text],
        n_results=n_results
    )
    incidents = []
    for i in range(len(results["documents"][0])):
        incidents.append({
            "document": results["documents"][0][i],
            "metadata": results["metadatas"][0][i],
            "distance": results["distances"][0][i]
        })
    return incidents

def score_pr_risk(diff_text):
    incidents = find_similar_incidents(diff_text)
    incidents_text = ""
    for i, incident in enumerate(incidents):
        meta = incident["metadata"]
        incidents_text += f"""
Incident {i+1} (Issue #{meta['issue_number']}):
Title: {meta['title']}
URL: {meta['url']}
Description: {incident['document'][:300]}
---
"""
    prompt = f"""You are a code review assistant that identifies production risks in PR diffs.

You have been given a PR diff and a set of similar past production incidents.

PR DIFF:
{diff_text}

SIMILAR PAST INCIDENTS:
{incidents_text}

You MUST respond using EXACTLY these section headers, each on their own line:

RISK_LEVEL: HIGH or MEDIUM or LOW

WHY_RISKY: 2-3 sentences explaining the specific risk.

RECOMMENDATION: 2-3 specific actionable things the developer should do.

INCIDENT_MATCH: One sentence explaining which past incident this most resembles and why.

Do not use any other formatting. Do not add extra sections. Start your response with RISK_LEVEL:"""

    response = ai_client.chat.completions.create(
        model="gemini-2.5-flash",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=2000
    )
    return {
        "analysis": response.choices[0].message.content,
        "incidents": incidents
    }

def extract_section(text, section):
    try:
        start = text.index(section + ":") + len(section) + 1
        next_sections = ["RISK_LEVEL", "WHY_RISKY", "RECOMMENDATION", "INCIDENT_MATCH"]
        end = len(text)
        for s in next_sections:
            if s + ":" in text[start:]:
                candidate = text.index(s + ":", start)
                if candidate < end:
                    end = candidate
        return text[start:end].strip()
    except ValueError:
        return "N/A"

def main():
    repo_name = os.getenv("GITHUB_REPOSITORY")
    pr_number = int(os.getenv("PR_NUMBER", 0))

    if not repo_name or not pr_number:
        print("Not running in GitHub Actions context")
        return

    repo = g.get_repo(repo_name)
    pr = repo.get_pull(pr_number)

    # Get the diff
    diff_text = ""
    for file in pr.get_files():
        diff_text += f"File: {file.filename}\n"
        if file.patch:
            diff_text += file.patch + "\n\n"

    if not diff_text:
        print("No diff found")
        return

    print(f"Analyzing PR #{pr_number}...")
    result = score_pr_risk(diff_text)

    # Parse the structured response
    analysis = result["analysis"]

    risk_level = extract_section(analysis, "RISK_LEVEL")
    why_risky = extract_section(analysis, "WHY_RISKY")
    recommendation = extract_section(analysis, "RECOMMENDATION")
    incident_match = extract_section(analysis, "INCIDENT_MATCH")

    # Pick emoji based on risk level
    if "HIGH" in risk_level:
        risk_emoji = "🔴"
    elif "MEDIUM" in risk_level:
        risk_emoji = "🟡"
    else:
        risk_emoji = "🟢"

    comment = f"""## 🤖 PR Risk Analysis

{risk_emoji} **Risk Level: {risk_level.strip()}**

### Why This Is Risky
{why_risky}

### Recommendation
{recommendation}

### Incident Match
{incident_match}

### Similar Past Incidents
"""
    for incident in result["incidents"]:
        meta = incident["metadata"]
        comment += f"- 🔗 [Issue #{meta['issue_number']}]({meta['url']}): {meta['title']}\n"

    comment += "\n---\n*Generated by PR Risk Scorer — powered by production incident history*"

    pr.create_issue_comment(comment)
    print("Comment posted!")

if __name__ == "__main__":
    main()